baseURL = "https://www.onthedrift.com"
languageCode = "en-us"
title = "On The Drift"
theme = "beautifulhugo"
enableRobotsTXT = true
disqusShortname = "onthedrift"
enableEmoji = true
enableGitInfo = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[Params]
  subtitle = "Comments and rants by yet another random developer"
  logo = "img/avatar-squared-nobody.png"
  favicon = "img/avatar-squared-nobody.ico"h 
  commit = "https://github.com/koenbeuk/onthedrift/tree/"
  rss = true
  comments = true
  readingTime = true
  socialShare = true
  showRelatedPosts = true
  hideAuthor = true
  useHLJS = true

[Author]
  name = "Koen"
  website = "https://www.onthedrift.com"
  email = "koen@linker.io"
  github = "koenbeuk"
  twitter = "onthedrift2"
  stackoverflow = "users/272424/polity"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
