baseURL = "https://onthedrift.com"
languageCode = "en-us"
title = "On the drift"
theme = "beautifulhugo"
enableRobotsTXT = true
disqusShortname = "onthedrift"
pygmentsCodeFences = true
pygmentsUseClasses = true
enableEmoji = true
enableGitInfo = true

[Params]
  subtitle = "A small site for simple samples & short sentences"
  logo = "img/avatar-squared.png"
  favicon = "img/avatar-squared.ico"
  commit = "https://github.com/koenbeuk/onthedrift/tree/"
  rss = true
  comments = true
  readingTime = true
  socialShare = true

[[Params.bigimg]]
  src = "img/avatar.svg"
  desc = "StaticmanLab + Hugo + KaTeX"
  position = "center"

[Author]
    name = "Koen"
    website = "https://www.onthedrift.com"
    email = "koen@linker.io"
    github = "koenbeuk"
    twitter = "onthedrift2"
    stackoverflow = "polity"